name: Check the NixOS flake

on:
    push:
        branches: [ master ]
        paths-ignore:
            - '.github/**'
            - 'LICENSE'
            - 'README.md'
    pull_request:
        branches: [ master ]
        paths-ignore:
            - '.github/**'
            - 'LICENSE'
            - 'README.md'

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install Nix
              uses: cachix/install-nix-action@v31

            - name: Set up cachix
              uses: cachix/cachix-action@v16
              with:
                  name: heartblin
                  authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

            - name: Run checks
              run: nix flake check --all-systems

